#!/usr/bin/env bash
set -euo pipefail

# ========= 配置 =========
DIR="./vscode-linux-x64-stable"
OUT_SH="vscode_version_commit.sh"
MIN_VERSION="1.81.1"
PRODUCT_JSON_PATH="VSCode-linux-x64/resources/app/product.json"
# =======================

FORCE=0

# -------- 参数解析 --------
for arg in "$@"; do
    case "$arg" in
        -f|--force) FORCE=1 ;;
        *)
            echo "Usage: $0 [-f|--force]"
            exit 1
            ;;
    esac
done

# -------- 语义版本比较 --------
version_ge() {
    local IFS=.
    # shellcheck disable=SC2206
    local v1=($1)
    # shellcheck disable=SC2206
    local v2=($2)
    local i
    for ((i=0; i<3; i++)); do
        ((10#${v1[i]} > 10#${v2[i]})) && return 0
        ((10#${v1[i]} < 10#${v2[i]})) && return 1
    done
    return 0
}

# -------- 加载已有 hash（若存在）--------
declare -A VSCODE_VERSION_COMMIT=()

if [[ -f "$OUT_SH" && "$FORCE" -eq 0 ]]; then
    # shellcheck source=/dev/null
    source "$OUT_SH"
fi

# FORCE 模式下清空
if [[ "$FORCE" -eq 1 ]]; then
    VSCODE_VERSION_COMMIT=()
fi

echo "[INFO] Min version : $MIN_VERSION"
echo "[INFO] Force       : $FORCE"
echo

# -------- 主解析逻辑 --------
for file in "${DIR}"/vscode-*-linux-x64.tar.gz; do
    [[ -f "$file" ]] || continue

    version="$(basename "$file" | sed -E 's/^vscode-([0-9]+\.[0-9]+\.[0-9]+)-.*/\1/')"
    [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || continue

    if ! version_ge "$version" "$MIN_VERSION"; then
        continue
    fi

    if [[ -n "${VSCODE_VERSION_COMMIT[$version]:-}" ]]; then
        echo "[SKIP] Exists: $version"
        continue
    fi

    if ! json="$(tar -xOzf "$file" "$PRODUCT_JSON_PATH" 2>/dev/null)"; then
        echo "[WARN] Missing product.json: $version"
        continue
    fi

    commit="$(jq -r '.commit // empty' <<< "$json")"
    [[ -n "$commit" && "$commit" != "null" ]] || continue

    VSCODE_VERSION_COMMIT["$version"]="$commit"
    echo "[OK]   Parsed: $version"
done

# -------- 输出为可 source 的 Bash 文件 --------
{
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by $(basename "$0") at $(date)"
    echo "# DO NOT EDIT MANUALLY"
    echo
    echo "declare -A VSCODE_VERSION_COMMIT=("

    for v in "${!VSCODE_VERSION_COMMIT[@]}"; do
        printf '  ["%s"]="%s"\n' "$v" "${VSCODE_VERSION_COMMIT[$v]}"
    done | sort -V

    echo ")"
} > "$OUT_SH"

chmod +x "$OUT_SH"

echo
echo "[DONE] Hash table written to $OUT_SH"
